language: php

php:
  - 5.5

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer --version
  - composer install --ignore-platform-reqs

script:
  # Run full test suite and linting of the code base
  - composer tests:all
